resolver: lts-7.13
extra-deps:
  - http-api-data-0.3.3
  - scotty-cookie-0.1.0.3
  - scotty-tls-0.4.1
packages:
  - location: .
  - location:
      git: https://gitlab.com/lightandlight/haskell-arrow-validation.git
      commit: HEAD
    extra-dep: true
